### ISSUE TITLE
Linking memrange (via metagoblin) causes GPL license violation

### ISSUE THREAD

**Issue by mgorny** [m4b/bingrep#22]
Disclaimer: IANAL. I'm trying my best to be correct but I may be wrong.

FWICS this package depends on metagoblin and theban_interval_tree, both of which in turn depend on memrange. Since memrange is GPL-3, it effectively requires any derivative work to be licensed GPL-3 as well. theban_interval_tree seems to try to do that. However, both metagoblin and bingrep specify only the MIT license.

if you wish to continue depending on memrange, I believe you need to redistribute both packages as GPL-3. I think you can still license the source files specific to those packages under the MIT license but the combined work must be licensed GPL-3.

**Comment by m4b** [comment]
Hey thanks for the feedback ! I really don’t know either, but this would be news to me (relicensing to gpl because a dep is gpl).

Afaik, I must only redistribute the source of the gpl dep if i modify it (which I don’t), but again I could be totally wrong.

Probably the easiest thing is to remove the theban interval dep in metagoblin (theban interval has got some broken issues that were never fixed anyway, iirc). Would you be interested in such a thing ? :)

**Comment by mgorny** [comment]
See e.g.: https://tldrlegal.com/license/gnu-general-public-license-v3-(gpl-3)

> Any modifications to or **software including (via compiler) GPL-licensed code** must also be made available under the GPL along with build & install instructions.

(highlight mine)

Yes, removing use of both deps sounds fine. I'm not sure what you mean by me being interested though. I'm merely on Gentoo's QA team and I'm helping our people with license problems lately. I don't have any stake in this particular package.

**Comment by m4b** [comment]
I just meant would you be interested in helping remove the deps, that’s all :) sounds like not.

I can take a look at this but I really don’t have a lot of time. Maybe some virtuous soul could come help ?

**Comment by m4b** [comment]
memrange is removed in metagoblin, along with interval tree crate (we didn't really use any interval tree logic anyway)
