### ISSUE TITLE
Doesn't work on COFF object files

### ISSUE THREAD

**Issue by bjorn3** [m4b/bingrep#36]
It gives `Unknown magic: 0x68664`. It works fine on PE executable files.

**Comment by m4b** [comment]
@koutheir would you have any insight on this, being the resident bingrep PE/COFF expert :D

**Comment by koutheir** [comment]
Can you please provide instructions on how to produce such a file?

**Comment by m4b** [comment]
@bjorn3 ^^^ if you could paste a file which exhibits this here, much appreciated!

**Comment by bjorn3** [comment]
Full reproducer:

```shell
$ rustup target add x86_64-pc-windows-gnu
info: downloading component 'rust-std' for 'x86_64-pc-windows-gnu'
info: installing component 'rust-std' for 'x86_64-pc-windows-gnu'
$ echo "" | rustc --target x86_64-pc-windows-gnu --emit obj - --crate-type lib
$ bingrep rust_out.o
Unknown magic: 0x38664
```

For completeness sake a reproducing file: [bingrep_coff.o.zip](https://github.com/m4b/bingrep/files/9234936/bingrep_coff.o.zip)

**Comment by koutheir** [comment]
This is failure of [`goblin::peek()`](https://docs.rs/goblin/latest/goblin/fn.peek.html) inside [bingrep::run()](https://github.com/m4b/bingrep/blob/a90ec92de2a94793042a5cd055be98240a9d4f4e/src/main.rs#L80). This issue needs to be fixed in [`goblin`](https://github.com/m4b/goblin), whose `peek()` function doesn't seem to support this COFF format.

**Comment by koutheir** [comment]
@bjorn3, can you please try out the behavior of this tool modified in [my fork](https://github.com/koutheir/bingrep) in order to test [my PR](https://github.com/m4b/bingrep/pull/37)?

**Comment by bjorn3** [comment]
It works. Thanks!
